name: No unresolved comments
on:
  pull_request_review_comment:

jobs:
  readResolutionStatus:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_comment_resolution_status
        with:
          query: |
            query release($owner:String!,$repo:String!, $pullrequest:Int!) {
              repository(owner:$owner,name:$repo) {
                pullRequest(number: $pullrequest) {
                  reviewThreads(last: 50) {
                    nodes {
                      isResolved
                    }
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          pullrequest: ${{ github.event.pull_request_review_comment.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run:
          "checkLength() { read length; if [ $length -gt 0 ]; then echo ::error ::There are $length unresolved comments; exit 1; fi; }; \
          echo '${{ steps.get_comment_resolution_status.outputs.data }}' | \
          jq '.repository.pullRequest.reviewThreads.nodes | map(select(.isResolved | not)) | length' | \
          checkLength"
        name: 'Unresolved Comments Check'
